### PR TITLE
Fixed projects section 

### PR DESCRIPTION
**Pull request by hritikadhikari05**
#57 Fixed design issue of project section

### CODE REVIEW

**Comment by thtauhid** [comment]
Hi @hritikadhikari05 please fix the button alignment 
image

**Comment by thtauhid** [comment]
Can you also fix https://github.com/thtauhid/open-profile/pull/65#issuecomment-1767768997 in this PR?

**Comment by thtauhid** [comment]
Can you also fix the sizing of the box? It does not match the other sizing of similar components?
image

**Comment by hritikadhikari05** [comment]
Hey @thtauhid , This issue has been fixed.
Please review it once.
Thank You!

**Pull request merged**
