### PR TITLE
Enhancement: using the context hook to update the document title of the current Page

### PR DESCRIPTION
**Pull request by kherin**
# Enhancement

Dynamically changing the document title based on the current page

### CODE REVIEW

**Review by thtauhid — CHANGES_REQUESTED** [review]
If I directly visit the link of any page the page title does not update.
Check https://open-profile-jgark6rvw-thtauhid.vercel.app/profile/thtauhid

Everything else looks good

**Comment by kherin** [comment]
> If I directly visit the link of any page the page title does not update. Check https://open-profile-jgark6rvw-thtauhid.vercel.app/profile/thtauhid
> 
> Everything else looks good

@thtauhid I made the fix. Now the page title is updated when navigating directly to the profile url

**Comment by thtauhid** [comment]
Looks good,

**Review by thtauhid — APPROVED** [review]
LGTM

**Pull request merged**
