### PR TITLE
Created new Workingon Component  

### PR DESCRIPTION
**Pull request by Shivampatil22**
**Feat : #7**  
### Create new workingOn Component
**### Component Picture**
image

### CODE REVIEW

**Comment by thtauhid** [comment]
@Shivampatil22 
1. Please remove the background color.
2. Use the basic button `src\components\ui\button.tsx`

**Comment by Shivampatil22** [comment]
### **Updated Component**
image

**Comment by thtauhid** [comment]
Hi @Shivampatil22 
Can you please fix the aligning?

image

image

**Comment by thtauhid** [comment]
@Shivampatil22 before creating new commit please merge the base branch to your feature branch and solve any merge conflicts. 
Thank you

**Comment by Shivampatil22** [comment]
Ok I will keep that in mind

**Pull request closed without merging**
