### PR TITLE
Add experience component

### PR DESCRIPTION
**Pull request by SAGARSINGH-1**
fix: #24 

Added a Experiance component which takse data from the API 

image

### CODE REVIEW

**Comment by randmon** [comment]
You have mispelled "Experience".

**Comment by SAGARSINGH-1** [comment]
@randmon Thanks to notice that, I'll Updated that.

**Comment by thtauhid** [comment]
From build log
image

Keep both the Testimonials component and the experience component.

**Comment by SAGARSINGH-1** [comment]
@thtauhid Updated

**Comment by thtauhid** [comment]
Please follow the image's instruction
image

**Comment by SAGARSINGH-1** [comment]
@thtauhid Updated the changes that you requested for.

**Review by thtauhid — CHANGES_REQUESTED** [review]
Move the page `src/api/Experiance.tsx` -> `src/pages/Profile/Experience.tsx`

Design is okay.

**Comment by SAGARSINGH-1** [comment]
@thtauhid Updated the path of the Experience component and added responsiveness to that Experience section

**Comment by thtauhid** [comment]
1. Can you fix the type `Experiance`. It should be `Experience`
2. Marge the base branch into your feature branch and resolve any conflicts.

**Comment by SAGARSINGH-1** [comment]
@thtauhid I am making another PR with all that changes.

**Pull request closed without merging**
