### PR TITLE
Added PWA functionality

### PR DESCRIPTION
**Pull request by half-real-SCRACX**
- added "pwa-asset-generator" module
- added "vite-plugin-pwa" module
- generated assets
- created PWA manifest
- configured anything else that was necessary

To be done: set a custom theme-color and background-color

### CODE REVIEW

**Comment by thtauhid** [comment]
This is the build log

```
[21:03:46.665] Running build in Washington, D.C., USA (East) – iad1 (Hive)
[21:03:46.900] Cloning github.com/thtauhid/open-profile (Branch: main, Commit: 226e542)
[21:03:47.358] Cloning completed: 456.695ms
[21:03:49.044] Restored build cache
[21:03:49.129] Running "vercel build"
[21:03:49.601] Vercel CLI 32.4.0
[21:03:50.291] Installing dependencies...
[21:03:55.872] npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
[21:03:57.047] npm WARN deprecated rollup-plugin-terser@7.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-terser
[21:03:58.541] 
[21:03:58.541] added 397 packages in 8s
[21:03:58.542] 
[21:03:58.542] 139 packages are looking for funding
[21:03:58.542]   run `npm fund` for details
[21:03:58.567] Detected `package-lock.json` generated by npm 7+
[21:03:58.567] Running "npm run build"
[21:03:59.033] 
[21:03:59.033] > open-profile@0.0.0 build
[21:03:59.033] > npm run generate-pwa-assets && tsc && vite build
[21:03:59.033] 
[21:03:59.344] 
[21:03:59.344] > open-profile@0.0.0 generate-pwa-assets
[21:03:59.344] > pwa-asset-generator ./src/assets/icons/favicon-source.png ./src/assets/icons/PWA -i ./index.html -m ./manifest.json --opaque false -s false -c true
[21:03:59.344] 
[21:03:59.693] 3:33:59 PM installer Chromium is not found in module folder, gonna have to download r982053 for you once 🤔
[21:04:00.752] 
[21:04:04.731] 3:34:04 PM installer Chromium downloaded to /vercel/path0/node_modules/puppeteer-core/.local-chromium/linux-982053
[21:04:04.809] 3:34:04 PM cli Error: Failed to launch the browser process!
[21:04:04.809] [1003/153404.799686:ERROR:zygote_host_impl_linux.cc(90)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
[21:04:04.809] 
[21:04:04.809] 
[21:04:04.809] TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
[21:04:04.809]  😭
[21:04:04.835] Error: Command "npm run build" exited with 1
```

image

**Comment by thtauhid** [comment]
This is the build log

```
[21:03:46.665] Running build in Washington, D.C., USA (East) – iad1 (Hive)
[21:03:46.900] Cloning github.com/thtauhid/open-profile (Branch: main, Commit: 226e542)
[21:03:47.358] Cloning completed: 456.695ms
[21:03:49.044] Restored build cache
[21:03:49.129] Running "vercel build"
[21:03:49.601] Vercel CLI 32.4.0
[21:03:50.291] Installing dependencies...
[21:03:55.872] npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
[21:03:57.047] npm WARN deprecated rollup-plugin-terser@7.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-terser
[21:03:58.541] 
[21:03:58.541] added 397 packages in 8s
[21:03:58.542] 
[21:03:58.542] 139 packages are looking for funding
[21:03:58.542]   run `npm fund` for details
[21:03:58.567] Detected `package-lock.json` generated by npm 7+
[21:03:58.567] Running "npm run build"
[21:03:59.033] 
[21:03:59.033] > open-profile@0.0.0 build
[21:03:59.033] > npm run generate-pwa-assets && tsc && vite build
[21:03:59.033] 
[21:03:59.344] 
[21:03:59.344] > open-profile@0.0.0 generate-pwa-assets
[21:03:59.344] > pwa-asset-generator ./src/assets/icons/favicon-source.png ./src/assets/icons/PWA -i ./index.html -m ./manifest.json --opaque false -s false -c true
[21:03:59.344] 
[21:03:59.693] 3:33:59 PM installer Chromium is not found in module folder, gonna have to download r982053 for you once 🤔
[21:04:00.752] 
[21:04:04.731] 3:34:04 PM installer Chromium downloaded to /vercel/path0/node_modules/puppeteer-core/.local-chromium/linux-982053
[21:04:04.809] 3:34:04 PM cli Error: Failed to launch the browser process!
[21:04:04.809] [1003/153404.799686:ERROR:zygote_host_impl_linux.cc(90)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
[21:04:04.809] 
[21:04:04.809] 
[21:04:04.809] TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
[21:04:04.809]  😭
[21:04:04.835] Error: Command "npm run build" exited with 1
```

image

**Comment by half-real-SCRACX** [comment]
I'm looking into it

**Comment by half-real-SCRACX** [comment]
So the problem is with the asset generation script.
It works with Puppeteer. There might be a problem with the sandboxing, and the fact that Vercel uses Linux. As the "Running as root without --no-sandbox is not supported. See https://crbug.com/638180." suggests, the "no sandbox" tag set to true in the asset generation script might solve the problem. On my machine, it works both ways.

**Comment by half-real-SCRACX** [comment]
The sandboxing was the problem. Fixed it, and now there are no errors!

**Comment by thtauhid** [comment]
Hi @half-real-SCRACX 
I know you have put in a lot of effort for this PR. 
But, there is a much better and more efficient way to implement PWA. 

You can follow this guideline: https://www.pupilfirst.school/targets/19703
If you are following this guide just avoid this part
```
As we are using vite to configure our PWA, we will not need an index.html served from our public folder as vite-plugin-pwa will pick the same from the project root folder.
```
You can use these [files](https://github.com/thtauhid/open-profile/files/12797580/favicon_io.zip) for the PWA.

Thanks for your interest and can't wait to see your new / updated PR. 

Regards
THT

**Comment by half-real-SCRACX** [comment]
Hey!
I looked over that post you sent, but I can't really understand what I should do differently... Also, I've tested the PWA with Lighthouse before creating the PR, and all the checks (like the performance ones) came out pretty good.
I'm looking forward to contributing to this repo, as I really like it and believe in it. Tell me what should be different and I'll fix/recreate it :)!

**Comment by thtauhid** [comment]
Hi @half-real-SCRACX 
I checked your PR. 
Please make the following changes-
1. All the icons should be in `public` folder. 

After putting all the icons in the public folder update the path of the icons too
image

image

2. We can safely remove the `pwa-asset-generator` package as we are going to use static assets located in `public` folder. 

image

**Comment by thtauhid** [comment]
Please make these two changes

image

image

**Pull request merged**
