### PR TITLE
Added a new testimonial component

### PR DESCRIPTION
**Pull request by Shivampatil22**
### **Component picture**
image

### CODE REVIEW

**Comment by thtauhid** [comment]
It is pending review. 
You'll receive an update in 30-45 mins.

**Comment by thtauhid** [comment]
Hi @Shivampatil22 
1. Can you please remove the animation?
2. Can you remove the shadow?
3. Please use the default button available in `src\components\ui\button.tsx`

**Comment by Shivampatil22** [comment]
### Updated Testimonial Component ****
image

**Review by thtauhid — APPROVED** [review]
LGTM

**Pull request merged**
